### ISSUE TITLE
can't see items in menu 

### ISSUE THREAD

**Issue by luke187** [Rinnegatamante/ZeldaOLB#1] opened 2017-06-01 06:09 UTC
When I press L + start the screen dims but nothing else changes on the screen and the items are not visible to see what items i have or where they are

**Comment by Rinnegatamante** [comment] 2017-06-01 07:24
Thanks for the report, the issue is under investigation. Should be solved soon.

**Comment by Rinnegatamante** [comment] 2017-06-01 09:34
Fixed with https://github.com/Rinnegatamante/ZeldaOLB/commit/3bbddb459e3a8f5cfbb0840225e060f8b55b828f .
I'm waiting for another user issue about 2nd boss to be addressed before releasing a bugfix version however.

**Closed as completed by Rinnegatamante** 2017-06-01 09:34 UTC
Labels: bug
